export const sharedStyles = {
    inputField: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '14px',
        lineHeight: '22px',
        color: '#303880',
        background: 'rgba(199, 199, 197, 0.25)',
        padding: '9px 8px',
        height: '40px',
        width: '563px',
    },
    label: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '14px',
        lineHeight: '22px',
        color: '#303880',
    },
    buttonCancel: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '14px',
        lineHeight: '22px',
        color: '#FD7118',
        background: 'transparent',
        border: 'none',
    },
    buttonSave: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: 700,
        fontSize: '14px',
        lineHeight: '22px',
        color: '#FFFFFF',
        background: '#FD7118',
        boxShadow: '2px 1px 2px rgba(0, 0, 0, 0.25)',
        borderRadius: '8px',
        width: '160px',
        height: '40px',
    },
    title: {
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '32px',
        lineHeight: '52px',
        color: '#0A1047',
    },
};
