import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@public/globals.css'
import { baseTheme } from '@/shared/ui'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { Roboto } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body
        className={roboto.variable}
        style={{
          background:
            'linear-gradient(to right, var(--mui-palette-primary-light) calc(50% - 600px + 243px), transparent calc(50% - 600px + 243px))',
        }}
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={baseTheme}>{children} </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
